AWSTemplateFormatVersion: '2010-09-09'
Description: 'Assignment 3 - EC2 Instance Template by Twinkle Mishra (8894858)'

Parameters:
  AMIId:
    Type: AWS::EC2::Image::Id
    Default: ami-0c02fb55956c7d316  # Amazon Linux 2 AMI in us-east-1
    Description: AMI ID for EC2 instance
  
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
  
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Default: assignment3-keypair

Resources:
  # Security Group for EC2 Instance
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Assignment3 EC2 instance - allows SSH
      VpcId: !ImportValue Assignment3-VPC-ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
          Description: Allow SSH access from anywhere
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0'
          Description: Allow HTTP access
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: '0.0.0.0/0'
          Description: Allow HTTPS access
      Tags:
        - Key: Name
          Value: Assignment3-EC2-SG-TwinkleMishra
        - Key: Student
          Value: Twinkle Mishra
        - Key: StudentID
          Value: '8894858'

  # EC2 Instance
  Assignment3EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      SubnetId: !ImportValue Assignment3-PublicSubnet-ID
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd mysql
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Assignment 3 - Twinkle Mishra (8894858)</h1>" > /var/www/html/index.html
          echo "<h2>EC2 Instance Successfully Deployed</h2>" >> /var/www/html/index.html
          echo "<p>Student: Twinkle Mishra</p>" >> /var/www/html/index.html
          echo "<p>Student ID: 8894858</p>" >> /var/www/html/index.html
      Tags:
        - Key: Dummy
          Value: ForceUpdate
        - Key: Name
          Value: Assignment3-EC2-TwinkleMishra
        - Key: Student
          Value: Twinkle Mishra
        - Key: StudentID
          Value: '8894858'
        - Key: Assignment
          Value: Assignment3

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref Assignment3EC2Instance
    Export:
      Name: Assignment3-EC2-InstanceId
  
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt Assignment3EC2Instance.PublicIp
    Export:
      Name: Assignment3-EC2-PublicIP
  
  PublicDNS:
    Description: Public DNS name of the EC2 instance
    Value: !GetAtt Assignment3EC2Instance.PublicDnsName
    Export:
      Name: Assignment3-EC2-PublicDNS
  
  SecurityGroupId:
    Description: Security Group ID for EC2 instance
    Value: !Ref EC2SecurityGroup
    Export:
      Name: Assignment3-EC2-SecurityGroup-ID